### YamlMime:Lifecycle
metadata:
  title: Microsoft intelligentne rakenduse lüüs 2007
  description: Microsoft intelligentne rakenduse lüüs 2007 järgib määratud elutsükli poliitikat.
  ms.date: 07/28/2020
  ms.openlocfilehash: 6e5cc4784788d27433b7525f6a900cbc1e9f0713
  ms.sourcegitcommit: 9bdc77ca92cba2e3edb432e57b1845247a9ade6e
  ms.translationtype: MT
  ms.contentlocale: et-EE
  ms.lasthandoff: 07/28/2020
  ms.locfileid: "813719"
name: Microsoft intelligentne rakenduse lüüs 2007
summary: >
  Microsoft intelligentne rakenduse lüüs 2007 järgib [määratud](/lifecycle/policies/fixed) elutsükli poliitikat.



  > [!IMPORTANT]

  > Selle toote tugi on lõppenud. Vt allpool teemast migreerimise juhised.
products:
- microsoft-servers
policyType: fixed
supportDates:
  start: 06/01/2007
  end: 07/10/2012
  extendedEnd: 07/11/2017
releases:
- version: Service Pack 2
  startDate: 11/27/2008
  endDate: 07/11/2017
- version: Service Pack 1
  startDate: 09/03/2007
  endDate: 01/12/2010
- version: Original Release
  startDate: 06/01/2007
  endDate: 10/14/2008
content: "\n## <a name=\"links\"></a>Lingid \n* [Microsoft intelligentne rakenduse lüüsi 2007 teejuht](/archive/blogs/testtesttestbug/important-changes-to-the-forefront-product-line)\n* [Hoolduspaketi poliitika](/lifecycle/policies/fixed#service-packs)"
