### YamlMime:Lifecycle
metadata:
  title: Microsoft Forefront Client Security
  description: Microsoft Forefront Client Security järgib fikseeritud elutsükli poliitikat.
  ms.date: 08/28/2020
  ms.openlocfilehash: d85aea21441458397839241e74939536051397d4
  ms.sourcegitcommit: 2bcdf249c9ef19aab3355f7dff4e0e020252ff76
  ms.translationtype: HT
  ms.contentlocale: et-EE
  ms.lasthandoff: 03/18/2022
  ms.locfileid: "4113404"
name: Microsoft Forefront Client Security
summary: >+
  Microsoft Forefront Client Security järgib [fikseeritud](/lifecycle/policies/fixed) elutsükli poliitikat.


products:
- msc
policyType: fixed
supportDates:
  start: 2007-08-02T00:00:00.000-08:00
  extendedEnd: 2015-07-14T22:59:59.999-08:00
releases:
- version: Original Release
  startDate: 2007-08-02T00:00:00.000-08:00
  endDate: 2015-07-14T22:59:59.999-08:00
content: "\n## <a name=\"links\"></a>Lingid \n* [System Center Endpoint Protection](/lifecycle/products/microsoft-system-center-2012-endpoint-protection)\n\n> [!NOTE]\n> Seisuga 14. juuli 2015 on Esefront Client Security pakkumine lõpetatud. Pärast tooteversiooni toe lõppu pole ründevaratõrje ja nuhkvaratõrje definitsiooni värskendused enam saadaval. Palun asendage see rakendusega System Center Endpoint Protection."
