### YamlMime:Lifecycle
metadata:
  title: Microsofti rakenduste virtualiseerimise 4,6
  description: Microsoft Application virtualiseerimine 4,6 järgib määratud elutsükli poliitikat.
  ms.date: 07/28/2020
  ms.openlocfilehash: 868274b4468e663afe8e1b9f36069490ab4da025
  ms.sourcegitcommit: 9bdc77ca92cba2e3edb432e57b1845247a9ade6e
  ms.translationtype: MT
  ms.contentlocale: et-EE
  ms.lasthandoff: 07/28/2020
  ms.locfileid: "813702"
name: Microsofti rakenduste virtualiseerimise 4,6
summary: >+
  Microsoft Application virtualiseerimine 4,6 järgib [määratud](/lifecycle/policies/fixed) elutsükli poliitikat.


  See kehtib järgmiste väljaannete kohta: Kaugtöölaua teenused, Windowsi lauaarvutid, Sequence

products:
- windows
policyType: fixed
supportDates:
  start: 05/27/2010
  end: 07/14/2015
  extendedEnd: 07/14/2020
releases:
- version: Service Pack 3
  startDate: 12/02/2013
  endDate: 07/14/2020
- version: Service Pack 2
  startDate: 10/01/2012
  endDate: 01/13/2015
- version: Service Pack 1
  startDate: 01/26/2011
  endDate: 10/08/2013
- version: Original Release
  startDate: 05/27/2010
  endDate: 04/10/2012
content: "\n## <a name=\"links\"></a>Lingid \n* [Toote-ja migreerimise teave](/microsoft-desktop-optimization-pack/appv-v4/overview-of-application-virtualization)\n* [Migreerimise juhised](https://techcommunity.microsoft.com/t5/Product-Life-Cycle/FAST-products-approaching-the-end-of-extended-support-in-2018/td-p/101710)\n* [Hoolduspaketi poliitika](/lifecycle/policies/fixed#service-packs)\n\n> [!NOTE]\n> Kuna App-V 4,6 Klient kasutab App-V 4,5 serverit, toetatakse rakendust-V 4,5 server vastavalt rakenduse-V 4,6 kasutusel olevatele elutsükli kuupäevadele, mis on kasutusel toetatud App-V 4,6 klientrakenduses.\n\n## <a name=\"editions\"></a>Väljaanded \n* Kaugtöölaua teenuste jaoks\n* Windowsi Lauaarvutid\n* Sequencer"
