### YamlMime:Lifecycle
metadata:
  title: Microsoft Forefront Client Security
  description: Microsoft Forefront Client Security järgib fikseeritud elutsükli poliitikat.
  ms.date: 08/28/2020
name: Microsoft Forefront Client Security
summary: |+
  Microsoft Forefront Client Security järgib [fikseeritud](/lifecycle/policies/fixed) elutsükli poliitikat.


products:
  - msc
policyType: fixed
supportDates:
  start: 08/02/2007
  extendedEnd: 07/14/2015
releases:
  - version: Original Release
    startDate: 08/02/2007
    endDate: 07/14/2015
content: |+

  ## <a name="links"></a>Lingid 
  * [System Center Endpoint Protection](/lifecycle/products/microsoft-system-center-2012-endpoint-protection)

  > [!NOTE]
  > Seisuga 14. juuli 2015 on Esefront Client Security pakkumine lõpetatud. Pärast tooteversiooni toe lõppu pole ründevaratõrje ja nuhkvaratõrje definitsiooni värskendused enam saadaval. Palun asendage see rakendusega System Center Endpoint Protection.