### YamlMime:Lifecycle
metadata:
  title: Microsoft Application Virtualization Hosting 5.1 for Windows Desktops
  description: Microsoft Application Virtualization Hosting 5.1 Windowsi töölaudadele järgib fikseeritud elutsükli poliitikat.
  ms.date: 09/10/2020
  keywords: for Windows Desktops
name: Microsoft Application Virtualization Hosting 5.1 for Windows Desktops
summary: |+
  Microsoft Application Virtualization Hosting 5.1 Windowsi töölaudadele järgib [fikseeritud](/lifecycle/policies/fixed) elutsükli poliitikat.

  See kehtib järgmiste väljaannete kohta: Windowsi töölaudade jaoks

products:
  - windows
policyType: fixed
supportDates:
  start: 11/01/2015
  end: 01/09/2018
  extendedEnd: 04/14/2026
releases:
  - version: Original Release
    startDate: 11/01/2015
    endDate: 04/14/2026
content: |

  ## <a name="links"></a>Lingid 
  * [Toote teave](/microsoft-desktop-optimization-pack/appv-v4/overview-of-application-virtualization)


  ## <a name="editions"></a>Väljaanded 
  * Windows töölaudade jaoks