### YamlMime:Lifecycle
metadata:
  title: Microsoft System Center Configuration Manager 2007 R3
  description: Microsoft System Center Configuration Manager 2007 R3 järgib fikseeritud elutsükli poliitikat.
  ms.date: 07/28/2020
name: Microsoft System Center Configuration Manager 2007 R3
summary: |
  Microsoft System Center Configuration Manager 2007 R3 järgib [fikseeritud](/lifecycle/policies/fixed) elutsükli poliitikat.


  > [!IMPORTANT]
  > Selle toote tugi on lõppenud. Vaadake allpool migreerimisjuhiseid.
products:
  - msc
policyType: fixed
supportDates:
  start: 12/19/2010
  end: 07/08/2014
  extendedEnd: 07/09/2019
releases:
  - version: Original Release
    startDate: 12/19/2010
    endDate: 07/09/2019
content: |+

  ## <a name="links"></a>Lingid 
  * [Migreerimise juhised](/mem/configmgr/core/migration/migrate-data-between-hierarchies)
  * [Täiendavad migreerimisjuhised](/mem/configmgr/core/migration/planning-for-migration)