### YamlMime:Lifecycle
metadata:
  title: Microsofti rakenduste virtualiseerimise hostimise 5,1 Windowsi lauaarvutite jaoks
  description: Microsofti rakenduste virtualiseerimise hostimise 5,1 Windowsi lauaarvutite jaoks järgib määratud elutsükli poliitikat.
  ms.date: 07/28/2020
  ms.openlocfilehash: c6fc257da84e3276165d0ab97a736120c1424172
  ms.sourcegitcommit: 6b0f0d4ac042ba924016a386cd23db5f1ed22756
  ms.translationtype: MT
  ms.contentlocale: et-EE
  ms.lasthandoff: 07/29/2020
  ms.locfileid: "852488"
name: Microsofti rakenduste virtualiseerimise hostimise 5,1 Windowsi lauaarvutite jaoks
summary: >+
  Microsofti rakenduste virtualiseerimise hostimise 5,1 Windowsi lauaarvutite jaoks järgib [määratud](/lifecycle/policies/fixed) elutsükli poliitikat.


  See kehtib järgmiste väljaannete kohta: Windowsi Lauaarvutid

products:
- windows
policyType: fixed
supportDates:
  start: 11/01/2015
  end: 01/09/2018
  extendedEnd: 04/14/2026
releases:
- version: Original Release
  startDate: 11/01/2015
  endDate: 04/14/2026
content: "\n## <a name=\"links\"></a>Lingid \n* [Toote teave](/microsoft-desktop-optimization-pack/appv-v4/overview-of-application-virtualization)\n\n\n## <a name=\"editions\"></a>Väljaanded \n* Windowsi Lauaarvutid"
