### YamlMime:Lifecycle
metadata:
  title: SoftGrid Application Virtualization
  description: SoftGrid Application Virtualization järgib fikseeritud elutsükli poliitikat.
  ms.date: 09/10/2020
  keywords: '4.1 for Desktops,4.2 for Desktops,for Terminal Services 4.1'
name: SoftGrid Application Virtualization
summary: |
  SoftGrid Application Virtualization järgib [fikseeritud](/lifecycle/policies/fixed) elutsükli poliitikat.

  See kehtib järgmiste väljaannete kohta: 4.1 lauaarvutitele, 4.2 lauaarvutitele, terminaliteenustele 4.1

  > [!IMPORTANT]
  > Tugi on lõppenud. Vaadake allpool migreerimisjuhiseid.
products:
  - windows
policyType: fixed
supportDates:
  start: 05/25/2007
  end: 07/10/2012
  extendedEnd: 07/11/2017
releases:
  - version: Original Release
    startDate: 05/25/2007
    endDate: 07/11/2017
content: |

  ## <a name="links"></a>Lingid 
  * [Migreerimise juhised](https://technet.microsoft.com/en-us/windows/bb899442)


  ## <a name="editions"></a>Väljaanded 
  * 4.1 lauaarvutitele
  * 4.2 lauaarvutitele
  * 4.1 terminaliteenuste jaoks