### YamlMime:Lifecycle
metadata:
  title: SoftGrid Application Virtualization
  description: SoftGrid Application Virtualization järgib fikseeritud elutsükli poliitikat.
  ms.date: 09/10/2020
  keywords: 4.1 for Desktops,4.2 for Desktops,for Terminal Services 4.1
  ms.openlocfilehash: 6b63a556c63bca08045d0335bd9233a0ae07a878
  ms.sourcegitcommit: 2bcdf249c9ef19aab3355f7dff4e0e020252ff76
  ms.translationtype: HT
  ms.contentlocale: et-EE
  ms.lasthandoff: 03/18/2022
  ms.locfileid: "4119842"
name: SoftGrid Application Virtualization
summary: >
  SoftGrid Application Virtualization järgib [fikseeritud](/lifecycle/policies/fixed) elutsükli poliitikat.


  See kehtib järgmiste väljaannete kohta: 4.1 lauaarvutitele, 4.2 lauaarvutitele, terminaliteenustele 4.1


  > [!IMPORTANT]

  > Tugi on lõppenud. Vaadake allpool migreerimisjuhiseid.
products:
- windows
policyType: fixed
supportDates:
  start: 2007-05-25T00:00:00.000-08:00
  end: 2012-07-10T22:59:59.999-08:00
  extendedEnd: 2017-07-11T22:59:59.999-08:00
releases:
- version: Original Release
  startDate: 2007-05-25T00:00:00.000-08:00
  endDate: 2017-07-11T22:59:59.999-08:00
content: "\n## <a name=\"links\"></a>Lingid \n* [Migreerimise juhised](https://technet.microsoft.com/en-us/windows/bb899442)\n\n\n## <a name=\"editions\"></a>Väljaanded \n* 4.1 lauaarvutitele\n* 4.2 lauaarvutitele\n* 4.1 terminaliteenuste jaoks"
